config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "homes#search"

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]

  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :categories
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy] 
   get "relationship/follow_users" => "relationships#follow_users"
   get "relationship/follower_users" => "relationships#follower_users"
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :categories, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
 def self.search(search_word)
    Book.where('title LIKE(?) OR body LIKE(?) OR category LIKE(?)', "%#{search_word}%", "%#{search_word}%", "%#{search_word}%")
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :book
  belongs_to :user
  
  validates :comment, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :book
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1
  }, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  #book,いいね,コメント,レビューのアソシエーション
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # フォロー機能部分のアソシエーション
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverse_of_relationships, source: :user

  #フォロー機能のメソッド
  #自分とフォロー先が一緒じゃないか検証
  def follow(other_user)
    unless self == other_user
    self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end
  # 既存のフォロワーならフォロー解除する
  def unfollow(other_user)
    relationships = self.relationships.find_by(follow_id: other_user.id)
    relationships.destroy if relationships
  end
  #フォロワーの中に含まれてない？
  def following?(other_user)
    self.followings.include?(other_user)
  end

  #プロフィール画像のattachment
  attachment :profile_image

  #validation
  validates :name, length: {in: 2..20}, uniqueness: { case_sensitive: false }
  validates :introduction ,length: {maximum: 50}

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!
   before_action :correct_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
   @books = Book.all.order(params[:sort])
   @user = current_user
   @book = Book.new
   @category = @book.category_id
  end

  def show
    @book = Book.new
    @book_comment = BookComment.new
    @book_detail = Book.find(params[:id])
    @user = current_user
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def update
    @book =Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path
    else
      @user = current_user
      @book_detail = Book.find(params[:id])
      render :edit
    end
  end

   def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
   end


  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :category)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top 
    end
    
    def about
    end
    
    def search
      @book = Book.new
      @books = Book.search(params[:keyword])
    end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @following = User.new
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user.id)
    else
       render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

  def correct_user
      @user = User.find(params[:id])
      redirect_to user_path(current_user) unless @user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/serches_helper.rb
module SerchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books_search.html.erb
<main>
 <table class = table>
    <thead>
        <tr>
            <th>Image</th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
        </tr>
    </thead>
    <tbody>
        <% books.each do |book| %>
         <tr>
            <td><%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td><%= book.category %></td>
         </tr>
        <% end %>
    </tbody>
</table>
</main>

app/views/books/_new.html.erb
  <!--新規投稿フォーム-->
  <h2 class="mt-3">New book</h2>
    <%= form_with model: book, local:true do |f| %>
    
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class:"form-control book_title" %>
      </div>
      
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class:"form-control book_opinion" %>
      </div>
      
      <div class="form-group">
        <label for="book_category">Category</label>
        <%= f.text_field :category, class:"form-control book_category" %>
      </div>
      
      <div class="form-group" id="star">
          <%= f.label :rate %>
          <%= f.hidden_field :rate, id: :review_star, class:'form-control' %>
        </div>
      
        <script>
        $('#star').raty({
          size     : 20,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'book[rate]',
          half: true,
        });
        </script>

        <%= f.submit 'Create Book', class:"btn btn-secondary  bg-success text-white" %>

    <% end %>

app/views/books/edit.html.erb
<main>
  
  <% if @book.errors.any? %>
  <div class = "text-danger h2">
    <%= @book.errors.count %> errors prohibited this obj from being saved:
  </div>
  <div>
    <li class = "text-danger">
    <% @book.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
    </li>
  <% end %>
  </div>

  <%= flash[:notice] %>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  	  	<h1>Editing Book</h1>
  	  	
      	<%= form_with model: @book, local:true do |f| %>
      	
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class:"form-control book_title" %>
        </div>
        
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class:"form-control book_opinion" %>
        </div>
        
        <div class="form-group">
          <label for="book_category">Category</label>
          <%= f.text_field :category, class:"form-control book_category" %>
        </div>
              
        <div class="form-group" id="rate_<%= @book.id %>"></div>
        <script>
          $('#rate_<%= @book.id %>').raty({
            size: 20,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @book.rate %>,
          });
        </script>
          
          <%= f.submit 'Update Book', class: "btn btn-secondary bg-success text-white" %>
        <% end %>

  		<%= link_to "Show",book_path(@book) %>
  		 | 
  		<%= link_to "Back",books_path %>

    </div>
  </div>
</main>

app/views/books/index.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<main>

   <% if @book.errors.any? %>
     <div class = "text-danger h2">
      <%= @book.errors.count %> errors prohibited this obj from being saved:
      </div>
    <li class = "text-danger">
        <% @book.errors.full_messages.each do |message| %>
        <%= message %>
        <% end %>
    <% end %>
    </li>

<div class="container px-5 px-sm-0">
  <div class = "row">
    <div class="col-md-3">
       <%= render "users/info", user: @user %>
       <%= render 'books/new', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <%= link_to "新しい順", books_path(sort: 'created_at DESC') %> |
        <%= link_to "評価の高い順", books_path(sort: 'rate DESC') %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <!--bookの投稿一覧-->
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td><%= link_to book.category, search_path(keyword: book.category) %></td>

          <!--いいね機能-->
            <td>
             <div id="favorites_buttons_<%= book.id %>">
              <%= render "favorites/favorite" , book: book %>
             </div>
            </td>
          
            <td><p>コメント数：<%= book.book_comments.count %></p></td>
            
            <!--星レビュー-->
            <td>
              <div id="rate_<%= book.id %>"></div>
              <script>
              $('#rate_<%= book.id %>').raty({
                size: 20,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= book.rate %>,
              });
              </script>
    				</td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/info', user: @book_detail.user %>
        <%= render 'books/new', book: @book %>
      </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
           <td>
             <%= attachment_image_tag @book_detail.user, :profile_image,fallback: "no_image.jpg", size:'40x40' %><br>
             <%= link_to @book_detail.user.name, user_path(@book_detail.user.id) %>
             </td>
           <td><%= link_to @book_detail.title, book_path %></td>
           <td><%= @book_detail.body %></td>
           <td><%= @book_detail.category %></td>

          <!--いいね機能-->
          <td>
            <div id="favorites_buttons_<%= @book_detail.id %>">
             <%= render "favorites/favorite" , book: @book_detail %>
            </div>
          </td>
          <td>
            <p>コメント数：<%= @book_detail.book_comments.count %></p>
          </td>
          
          <!--星レビュー-->
          <td>
            <div id="rate_<%= @book_detail.id %>"></div>
            <script>
              $('#rate_<%= @book_detail.id %>').raty({
                size: 20,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @book_detail.rate %>,
              });
            </script>
          </td>
           <td>
             <% if @book_detail.user == current_user %>
              <%= link_to "Edit", edit_book_path(@book_detail), class: "btn btn-sm btn-secondary bg-success text-white"%>
             <% end %>
          </td>
          <td>
              <% if @book_detail.user == current_user %>
                <%= link_to "Destroy", book_path(@book_detail), method: :delete,class: "btn btn-sm btn-secondary bg-danger text-white" ,"data-confirm" => "本当に削除しますか？"%>
              <% end %>
          </td>
        </tr>

          <!--コメント機能-->
          <tbody>
          <tr class = "CommentsArea">
             <%= render "book_comments/comment", book_detail: @book_detail, book_comment: @book_comment %>
          </tr>
          <tr>
            <td class = "InputComment">
              <%= form_with(model:[@book_detail, @book_comment], remote: true) do |f| %>
                <div class="form-group">
                  <%=f.text_area:comment,rows:"5" ,class:"form-control" %>
                </div>
                <%= f.submit "送信" %>
              <% end %>
            </td>
          </tr>
          </tbody>
        </tbody>
      </table>
    </div>
  </div>
</main>

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
     <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>

app/views/homes/search.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<main>
<div class="container px-5 px-sm-0">
  <div class = "row">
    <div class="col-md-3">
       <%= render "users/info", user: @user %>
       <%= render 'books/new', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
        <%= link_to "新しい順", books_path(sort: 'created_at DESC') %> |
        <%= link_to "評価の高い順", books_path(sort: 'rate DESC') %>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th>Category</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <!--bookの投稿一覧-->
        <% @books.each do |book| %>
          <tr>
            <td><%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size:'40x40' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td><%= link_to book.category, search_path(keyword: book.category) %></td>

          <!--いいね機能-->
            <td>
             <div id="favorites_buttons_<%= book.id %>">
              <%= render "favorites/favorite" , book: book %>
             </div>
            </td>
          
            <td><p>コメント数：<%= book.book_comments.count %></p></td>
            
            <!--星レビュー-->
            <td>
              <div id="rate_<%= book.id %>"></div>
              <script>
              $('#rate_<%= book.id %>').raty({
                size: 20,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= book.rate %>,
              });
              </script>
    				</td>
          </tr>
        <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>

<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
          <div class="btn-wrapper col-10 mx-auto">
            <div class="row">
              <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3" %>
            </div>
            <div class="row">
                <%= link_to "Sign Up", new_user_registration_path,class:"btn btn-success btn-sm btn-block" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

app/views/users/_info.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>

<!--ログインしているユーザー情報-->
 <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size:'80x80' %>
  <table class="table">
    <tbody>

      <tr>
	      <th>name</th>
	      <th><%= current_user.name %></th>
      </tr>

      <tr>
	      <th>introduction</th>
	      <th><%= current_user.introduction %></th>
      </tr>

      <tr>
        <!--フォロー・フォロワー欄-->
      <!--  <th>follows</th>-->
      <!--  <th><#%= link_to current_user.followings.count, relationship_follow_users_path(follow_id: user.id) %></th>-->
      <!--</tr>-->
      <!--<tr>-->
      <!--  <th>followers</th>-->
      <!--  <th><%#= link_to current_user.followers.count, relationship_follower_users_path(follow_id: user.id) %></th>-->
      <!--</tr>-->

    </tbody>
  </table>
  <div class="row">
    <% if user == current_user %>
      <%= link_to "", edit_user_path(user) , class:"btn btn-outline-secondary btn-block fas fa-user-cog"%>
    <% end %>
  </div>

app/views/users/_users_search.html.erb
<main>
<table>
    <thead>
        <tr>
            <th>image</th>
            <th>name</th>
            <th>introduction</th>
        </tr>
    </thead>
    <tbody id ="user">
        <% users.each do |user| %>
        <tr>
            <td>
            <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size:'40x50' %>
            </td>
            <td><%= link_to user_path(user) do %>
                <%= user.name %>
                <% end %>
            </td>
            <td><%= user.introduction %></td>
        </tr>
        <% end %>
    </tbody>
</table>
</main>

app/views/users/edit.html.erb
 


<main>
 
   <% if @user.errors.any? %>
   <div class = "text-danger h2">
    <%= @user.errors.count %> errors prohibited this obj from being saved:
  </div>
    <li class = "text-danger ">
    <% @user.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>
  </li>
  
  <div class="container">
    <div class="row">
     <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>

     <%= form_with model: @user, local:true do |f| %>

      <label for="user_name">Name</label>
       <%= f.text_field :name, class: "form-control name" %>

       <label for="user_image">Image</label>
       <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>

       <label for="user_introduction">Introduction</label>
       <%= f.text_area :introduction ,class: "form-control introduction" %>

        <%= f.submit "Update User", class: "btn btn-secondary bg-secondary text-white" %>

      <% end %>
      </div>
     </div>
  </div>
</main>

app/views/users/index.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>
<p id="notice"></p>
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render "users/info", user: @user %> <!--ログイン者情報-->
        <%= render 'books/new', book: @book %> <!--投稿情報-->
      </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
          <tbody>
             <% @users.each do |user| %>
            <tr>
                <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size:'40x50'%></td>
                <td><%= user.name %></td>

                <!--フォローフォロワー機能-->

                <td>
                  <p>フォロー数：<%= user.followings.count %></p>
                </td>
                 <td>
                  <p>フォロワー数：<%= user.followings.count %></p>
                </td>
                <td>
                  <% unless current_user == user %>

                   <% if current_user.following?(user) %>
                     <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
                       <%= hidden_field_tag :follow_id, user.id %>
                       <%= f.submit 'フォローを外す', class: 'btn btn-secondary  bg-info text-white' %>
                     <% end %>

                   <% else %>

                     <%= form_for(current_user.relationships.build) do |f| %>
                       <%= hidden_field_tag :follow_id, user.id %>
                       <%= f.submit 'フォローする', class: 'btn btn-secondary  bg-success text-white' %>
                     <% end %>
                   <% end %>

                  <% end %>
                </td>

                <td><%= link_to "Show", user_path(user) %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<script src="https://kit.fontawesome.com/f03fd448b3.js" crossorigin="anonymous"></script>

<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render "users/info", user: @user %>
        <%= render "relationships/follow", user: @user %>
        <%= render 'books/new', book: @book %>
      </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th>title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
          <tbody>
             <% @books.each do |book| %>
            <tr>
                <td><%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size:'40x50' %>
                  <% end %></td>
                <td><%= link_to book.title, book_path(book) %></td>
                <td><%= book.body %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
</main>